name: Build WebGL

on:
  push:
    branches:
      - main  # Runs when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build
          path: build/WebGL
